/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";
import * as core from "../../../core";

export const BaseLeg: core.schemas.ObjectSchema<BaseLeg.Raw, ClimatiqApi.flights.BaseLeg> = core.schemas.object({
  from: core.schemas.string(),
  to: core.schemas.string(),
});

export declare namespace BaseLeg {
  interface Raw {
    from: string;
    to: string;
  }
}
