/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const FreightFlightsRequest: core.schemas.ObjectSchema<
  FreightFlightsRequest.Raw,
  ClimatiqApi.flights.FreightFlightsRequest
> = core.schemas.object({
  legs: core.schemas.list(core.schemas.lazyObject(() => serializers.flights.FreightLeg)),
});

export declare namespace FreightFlightsRequest {
  interface Raw {
    legs: serializers.flights.FreightLeg.Raw[];
  }
}
