/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const FreightLeg: core.schemas.ObjectSchema<FreightLeg.Raw, ClimatiqApi.flights.FreightLeg> = core.schemas
  .object({
    weight: core.schemas.number(),
    weightUnit: core.schemas.property("weight_unit", core.schemas.string()),
    emissionFactor: core.schemas.property(
      "emission_factor",
      core.schemas.lazyObject(() => serializers.estimation.EmissionSelector)
    ),
  })
  .extend(core.schemas.lazyObject(() => serializers.flights.BaseLeg));

export declare namespace FreightLeg {
  interface Raw extends serializers.flights.BaseLeg.Raw {
    weight: number;
    weight_unit: string;
    emission_factor: serializers.estimation.EmissionSelector.Raw;
  }
}
