/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const TravelLeg: core.schemas.ObjectSchema<TravelLeg.Raw, ClimatiqApi.flights.TravelLeg> = core.schemas
  .object({
    passengers: core.schemas.number().optional(),
    class: core.schemas.string().optional(),
    emissionFactor: core.schemas.property(
      "emission_factor",
      core.schemas.lazyObject(() => serializers.estimation.EmissionSelector).optional()
    ),
  })
  .extend(core.schemas.lazyObject(() => serializers.flights.BaseLeg));

export declare namespace TravelLeg {
  interface Raw extends serializers.flights.BaseLeg.Raw {
    passengers?: number | null;
    class?: string | null;
    emission_factor?: serializers.estimation.EmissionSelector.Raw | null;
  }
}
