/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const TripEmissions: core.schemas.ObjectSchema<TripEmissions.Raw, ClimatiqApi.flights.TripEmissions> =
  core.schemas.object({
    co2E: core.schemas.property("co2e", core.schemas.number()),
    cot2EUnit: core.schemas.property("cot2e_unit", core.schemas.string()),
    legs: core.schemas.list(core.schemas.lazyObject(() => serializers.estimation.EstimateResponse)),
  });

export declare namespace TripEmissions {
  interface Raw {
    co2e: number;
    cot2e_unit: string;
    legs: serializers.estimation.EstimateResponse.Raw[];
  }
}
