/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { ClimatiqApi } from "../../..";
import * as core from "../../../core";

export const Request: core.schemas.Schema<
  serializers.customActivities.customActivityRequest.Raw[],
  ClimatiqApi.customActivities.customActivityRequest[]
> = core.schemas.list(core.schemas.lazyObject(() => serializers.customActivities.customActivityRequest));
