/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { ClimatiqApi } from "../../..";
import * as core from "../../../core";

export const Request: core.schemas.Schema<
  serializers.estimation.EstimateRequest.Raw[],
  ClimatiqApi.estimation.EstimateRequest[]
> = core.schemas.list(core.schemas.lazyObject(() => serializers.estimation.EstimateRequest));
