/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const BatchEstimateResponse: core.schemas.ObjectSchema<
  BatchEstimateResponse.Raw,
  ClimatiqApi.estimation.BatchEstimateResponse
> = core.schemas.object({
  response: core.schemas.list(core.schemas.lazy(() => serializers.estimation.BatchItemEstimate)),
});

export declare namespace BatchEstimateResponse {
  interface Raw {
    response: serializers.estimation.BatchItemEstimate.Raw[];
  }
}
