/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";
import * as core from "../../../core";

export const CalculationMethod: core.schemas.Schema<CalculationMethod.Raw, ClimatiqApi.estimation.CalculationMethod> =
  core.schemas.string().transform<ClimatiqApi.estimation.CalculationMethod>({
    parse: (value) => ClimatiqApi.estimation.CalculationMethod._parse(value),
    json: ({ value }) => value,
  });

export declare namespace CalculationMethod {
  type Raw = string;
}
