/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";
import * as core from "../../../core";

export const ConstituentGases: core.schemas.ObjectSchema<
  ConstituentGases.Raw,
  ClimatiqApi.estimation.ConstituentGases
> = core.schemas.object({
  co2ETotal: core.schemas.property("co2e_total", core.schemas.number().optional()),
  co2EOther: core.schemas.property("co2e_other", core.schemas.number().optional()),
  co2: core.schemas.number().optional(),
  ch4: core.schemas.number().optional(),
  n2O: core.schemas.property("n2o", core.schemas.number().optional()),
});

export declare namespace ConstituentGases {
  interface Raw {
    co2e_total?: number | null;
    co2e_other?: number | null;
    co2?: number | null;
    ch4?: number | null;
    n2o?: number | null;
  }
}
