/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const EmissionSelector: core.schemas.ObjectSchema<
  EmissionSelector.Raw,
  ClimatiqApi.estimation.EmissionSelector
> = core.schemas.object({
  activityId: core.schemas.property("activity_id", core.schemas.string()),
  source: core.schemas.string().optional(),
  region: core.schemas.string().optional(),
  regionFallback: core.schemas.property("region_fallback", core.schemas.boolean().optional()),
  year: core.schemas.string().optional(),
  lcaActivity: core.schemas.property("lca_activity", core.schemas.string().optional()),
  calculationMethod: core.schemas.property(
    "calculation_method",
    core.schemas.lazy(() => serializers.estimation.CalculationMethod).optional()
  ),
});

export declare namespace EmissionSelector {
  interface Raw {
    activity_id: string;
    source?: string | null;
    region?: string | null;
    region_fallback?: boolean | null;
    year?: string | null;
    lca_activity?: string | null;
    calculation_method?: serializers.estimation.CalculationMethod.Raw | null;
  }
}
