/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const EstimateRequest: core.schemas.ObjectSchema<EstimateRequest.Raw, ClimatiqApi.estimation.EstimateRequest> =
  core.schemas.object({
    emissionFactor: core.schemas.property(
      "emission_factor",
      core.schemas.lazyObject(() => serializers.estimation.EmissionSelector)
    ),
    parameters: core.schemas.unknown(),
  });

export declare namespace EstimateRequest {
  interface Raw {
    emission_factor: serializers.estimation.EmissionSelector.Raw;
    parameters?: unknown;
  }
}
