/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";
import * as core from "../../../core";

export const EstimateError: core.schemas.ObjectSchema<EstimateError.Raw, ClimatiqApi.estimation.EstimateError> =
  core.schemas.object({
    error: core.schemas.string(),
    message: core.schemas.string(),
  });

export declare namespace EstimateError {
  interface Raw {
    error: string;
    message: string;
  }
}
