/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";

export interface ClassificationRequest {
  classification: ClimatiqApi.classifications.ClassificationSelector;
  parameters: Record<string, string>;
}
