/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";

/**
 * A selector with classification data
 */
export interface ClassificationSelector {
  /** The classification code. */
  classificationCode: string;
  /** The classification scheme; currently supported are nace2 or isic4. */
  classificationType: string;
  /** Emission factor data source name. */
  source?: string;
  /** Geographic region to which the emission factor applies. */
  region?: string;
  /** Set this to true if you're willing to accept a less specific geographical region than the one you've specified. Climatiq will then attempt to fall back to the larger region if it does not find any emission factors with the initial region. Default is false */
  regionFallback?: boolean;
  /** Year for which the emission factor applies. */
  year?: string;
  /** The Life Cycle Assessment (LCA) activity to which this factor is associated. */
  lcaActivity?: string;
  /** The calculation method that will be used to calculate the CO2e emission factor. */
  calculationMethod?: ClimatiqApi.estimation.CalculationMethod;
}
