/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";
import * as core from "../../../core";

export interface Request {
  /** Where the :provider path argument must be replaced with the id of the supported cloud providers. */
  provider: ClimatiqApi.cloudComputing.ProviderId;
  _body: ClimatiqApi.cloudComputing.MemoryRequest;
}

export type Response = core.APIResponse<
  ClimatiqApi.estimation.EstimateResponse,
  ClimatiqApi.cloudComputing.memory.Error
>;
export type Error = Error._Unknown;

export declare namespace Error {
  interface _Unknown extends _Utils {
    errorName: void;
    content: core.Fetcher.Error;
  }

  interface _Utils {
    _visit: <Result>(visitor: Error._Visitor<Result>) => Result;
  }

  interface _Visitor<Result> {
    _other: (value: core.Fetcher.Error) => Result;
  }
}
