/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const ClassificationRequest: core.schemas.ObjectSchema<
  ClassificationRequest.Raw,
  ClimatiqApi.classifications.ClassificationRequest
> = core.schemas.object({
  classification: core.schemas.lazyObject(() => serializers.classifications.ClassificationSelector),
  parameters: core.schemas.record(core.schemas.string(), core.schemas.string()),
});

export declare namespace ClassificationRequest {
  interface Raw {
    classification: serializers.classifications.ClassificationSelector.Raw;
    parameters: Record<string, string>;
  }
}
