/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";

export interface EmissionFactor {
  /** The unique ID describing this particular emission factor. */
  uuid: string;
  /** The ID describing the activity that this emission factor applies to. Multiple emission factors can share the same activity_id, e.g. if they are from a different source or apply to a different region. */
  activityId: string;
  /** A deprecated alias for activity_id. Use activity_id instead, as this will be removed in the next version. */
  id: string;
  /** Whether or not the data is publicly available or private to your project. Can be either private or public. Public emission factors are available to all, while private emission factors are only accessible to you. */
  accessType: string;
  /** Emission factor name. */
  name: string;
  /** Emission factor category. */
  category: string;
  /** Emission factor sector. */
  sector: string;
  /** Emission factor publisher. */
  source: string;
  /** Link to emission factor publisher. */
  sourceLink: string;
  /** Emission factor uncertainty factor (%). */
  uncertainty?: number;
  /** Year for which the emission factor applies. */
  year: string;
  /** Geographic region to which the emission factor applies (UN/LOCODE). */
  region: string;
  /** Geographic region to which the emission factor applies (in English). */
  regionName: string;
  /** Emission factor description. */
  description: string;
  /** A list of Unit types that this emission factor accepts. */
  unitType: string[];
  /** The unit in which the factor field is expressed. */
  unit: string;
  /** Which LCA activity the emission factor corresponds to. Read more about life cycle assessments here. */
  lcaActivity: string;
  /** The methods of CO2e calculation supported for this emission factor */
  supportedCalculationMethods: string[];
  /** CO2e emission factor value, expressed in kgCO2e emitted per unit of activity provided in the unit field */
  factor: number;
  /** Indicates which conversion values were used (IPCC 4th or 5th Assessment Report) to generate the returned CO2e emission factor */
  factorCalculationMethod: ClimatiqApi.estimation.CalculationMethod;
  /** Indicates whether the CO2e emission factor provided in this response was provided by the source or calculated by Climatiq */
  factorCalculationOrigin: ClimatiqApi.emissionFactor.FactorCalculationOrigin;
  /** Indicates which gases the CO2e emission factor is composed of. */
  constituentGases: ClimatiqApi.estimation.ConstituentGases;
}
