/**
 * This file auto-generated by Fern from our API Definition.
 */

export interface LcaActivitiesResponse {
  /** List of life cycle assessment activities available for the given query. */
  results: string[];
}
