/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";

export interface PossibleEmissionFactorFilters {
  /** Filters emission factors by year factor applies to */
  year: string[];
  /** Filters emission factors by data source */
  source: string[];
  /** Filters emission factors by geographic region */
  region: ClimatiqApi.emissionFactor.Region[];
  /** Filters by emission factor category */
  category: string[];
  /** Filters by emission factor sector */
  sector: string[];
  /** Filters by unit type */
  unitType: string[];
}
