/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";

export interface RegionsResponse {
  /** List of regions available for the given query. */
  results: ClimatiqApi.emissionFactor.Region[];
}
