/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";
import * as core from "../../../core";

export const BaseRequest: core.schemas.ObjectSchema<BaseRequest.Raw, ClimatiqApi.cloudComputing.BaseRequest> =
  core.schemas.object({
    region: core.schemas.string(),
    durationUnit: core.schemas.property("duration_unit", core.schemas.string().optional()),
  });

export declare namespace BaseRequest {
  interface Raw {
    region: string;
    duration_unit?: string | null;
  }
}
