/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";
import * as core from "../../../core";

export const CloudProviderMetadata: core.schemas.ObjectSchema<
  CloudProviderMetadata.Raw,
  ClimatiqApi.cloudComputing.CloudProviderMetadata
> = core.schemas.object({
  providerFullName: core.schemas.property("provider_full_name", core.schemas.string()),
  providerId: core.schemas.property("provider_id", core.schemas.string()),
  cpuRegions: core.schemas.property("cpu_regions", core.schemas.list(core.schemas.string())),
  storageRegions: core.schemas.property("storage_regions", core.schemas.list(core.schemas.string())),
  memoryRegions: core.schemas.property("memory_regions", core.schemas.list(core.schemas.string())),
});

export declare namespace CloudProviderMetadata {
  interface Raw {
    provider_full_name: string;
    provider_id: string;
    cpu_regions: string[];
    storage_regions: string[];
    memory_regions: string[];
  }
}
