/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";
import * as core from "../../../core";

export const CloudProvider: core.schemas.Schema<CloudProvider.Raw, ClimatiqApi.cloudComputing.CloudProvider> =
  core.schemas.string().transform<ClimatiqApi.cloudComputing.CloudProvider>({
    parse: (value) => ClimatiqApi.cloudComputing.CloudProvider._parse(value),
    json: ({ value }) => value,
  });

export declare namespace CloudProvider {
  type Raw = string;
}
