/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";
import * as core from "../../../core";

export const ProviderId: core.schemas.Schema<ProviderId.Raw, ClimatiqApi.cloudComputing.ProviderId> =
  core.schemas.string();

export declare namespace ProviderId {
  type Raw = string;
}
