/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";
import * as core from "../../../core";

export const StorageType: core.schemas.Schema<StorageType.Raw, ClimatiqApi.cloudComputing.StorageType> = core.schemas
  .string()
  .transform<ClimatiqApi.cloudComputing.StorageType>({
    parse: (value) => ClimatiqApi.cloudComputing.StorageType._parse(value),
    json: ({ value }) => value,
  });

export declare namespace StorageType {
  type Raw = string;
}
