/**
 * This file auto-generated by Fern from our API Definition.
 */

export interface BaseLeg {
  /** Start of flight leg, expressed in an IATA code */
  from: string;
  /** End of flight leg, expressed in an IATA code */
  to: string;
}
