/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";

export interface TravelLeg extends ClimatiqApi.flights.BaseLeg {
  /** How many passengers are on the flight? Default is 1 */
  passengers?: number;
  /** Which class the flight was on. */
  class?: string;
  /** This endpoint will automatically pick the highest emission factor which is eligible for the flight. If you want to override the automatic emission factor selection you can provide a selector. You are then fully responsible for emission factor selection. The selector must end up selecting an emission factor that supports the PassengerOverDistance unit. */
  emissionFactor?: ClimatiqApi.estimation.EmissionSelector;
}
