/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";

export interface TripEmissions {
  /** Total carbon dioxide equivalent for entire trip. */
  co2E: number;
  /** The unit in which the co2e field is expressed. */
  cot2EUnit: string;
  /** List of estimations, one for each leg in the trip. These are returned in the same order as the flight legs. */
  legs: ClimatiqApi.estimation.EstimateResponse[];
}
