/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";

export interface BatchEstimateResponse {
  /** List of results for every operation. */
  response: ClimatiqApi.estimation.BatchItemEstimate[];
}
