/**
 * This file auto-generated by Fern from our API Definition.
 */

export interface ConstituentGases {
  /** The total amount of GHG emitted per unit of activity expressed as kgCO2e, as reported by the source. It is null for Climatiq-performed calculations. */
  co2ETotal?: number;
  /** The total amount of GHG emitted that are not CO2, CH4 or N20 - expressed in kgCO2e emitted per unit of activity, as reported by the source. */
  co2EOther?: number;
  /** The amount of carbon dioxide (CO2) emitted per unit of activity expressed as kgCO2, as reported by the source. */
  co2?: number;
  /** The amount of methane (CH4) emitted per unit of activity expressed as kgCH4, as reported by the source. */
  ch4?: number;
  /** The amount of nitrous oxide (N2O) emitted per unit of activity expressed as kgN2O, as reported by the source. */
  n2O?: number;
}
