/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";

export interface EstimateRequest {
  /** Emission factor ID or selection parameters selector. */
  emissionFactor: ClimatiqApi.estimation.EmissionSelector;
  /** Emission factor parameters. The parameter object changes depending on the EF selected. */
  parameters?: unknown;
}
