/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";

export interface EstimateResponse {
  co2E: number;
  co2EUnit: string;
  co2ECalculationMethod: string;
  co2ECalculationOrigin: string;
  emissionFactor: ClimatiqApi.estimation.UsedEmissionFactor;
  constituentGases: ClimatiqApi.estimation.ConstituentGases;
}
