/**
 * This file auto-generated by Fern from our API Definition.
 */

export interface UsedEmissionFactor {
  activityId: string;
  source: string;
  year: string;
  region: string;
  category: string;
  lcaActivity: string;
}
