/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";

export interface batchCustomActivitiesResponse {
  results: ClimatiqApi.estimation.EstimateResponse[];
}
