/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";
import * as core from "../../../core";

export const CategoriesResponse: core.schemas.ObjectSchema<
  CategoriesResponse.Raw,
  ClimatiqApi.emissionFactor.CategoriesResponse
> = core.schemas.object({
  results: core.schemas.list(core.schemas.string()),
});

export declare namespace CategoriesResponse {
  interface Raw {
    results: string[];
  }
}
