/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";
import * as core from "../../../core";

export const FactorCalculationOrigin: core.schemas.Schema<
  FactorCalculationOrigin.Raw,
  ClimatiqApi.emissionFactor.FactorCalculationOrigin
> = core.schemas.string().transform<ClimatiqApi.emissionFactor.FactorCalculationOrigin>({
  parse: (value) => ClimatiqApi.emissionFactor.FactorCalculationOrigin._parse(value),
  json: ({ value }) => value,
});

export declare namespace FactorCalculationOrigin {
  type Raw = string;
}
