/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";
import * as core from "../../../core";

export const Region: core.schemas.ObjectSchema<Region.Raw, ClimatiqApi.emissionFactor.Region> = core.schemas.object({
  id: core.schemas.string(),
  name: core.schemas.string(),
});

export declare namespace Region {
  interface Raw {
    id: string;
    name: string;
  }
}
