/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";
import * as core from "../../../core";

export const SectorsResponse: core.schemas.ObjectSchema<
  SectorsResponse.Raw,
  ClimatiqApi.emissionFactor.SectorsResponse
> = core.schemas.object({
  results: core.schemas.list(core.schemas.string()),
});

export declare namespace SectorsResponse {
  interface Raw {
    results: string[];
  }
}
