/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";
import * as core from "../../../core";

export const UnitTypesResponse: core.schemas.ObjectSchema<
  UnitTypesResponse.Raw,
  ClimatiqApi.emissionFactor.UnitTypesResponse
> = core.schemas.object({
  results: core.schemas.list(core.schemas.string()),
});

export declare namespace UnitTypesResponse {
  interface Raw {
    results: string[];
  }
}
