/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";
import * as core from "../../../core";

export const YearsResponse: core.schemas.ObjectSchema<YearsResponse.Raw, ClimatiqApi.emissionFactor.YearsResponse> =
  core.schemas.object({
    results: core.schemas.list(core.schemas.string()),
  });

export declare namespace YearsResponse {
  interface Raw {
    results: string[];
  }
}
