/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const batchCustomActivitiesResponse: core.schemas.ObjectSchema<
  batchCustomActivitiesResponse.Raw,
  ClimatiqApi.customActivities.batchCustomActivitiesResponse
> = core.schemas.object({
  results: core.schemas.list(core.schemas.lazyObject(() => serializers.estimation.EstimateResponse)),
});

export declare namespace batchCustomActivitiesResponse {
  interface Raw {
    results: serializers.estimation.EstimateResponse.Raw[];
  }
}
