/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const customActivitySelector: core.schemas.ObjectSchema<
  customActivitySelector.Raw,
  ClimatiqApi.customActivities.customActivitySelector
> = core.schemas.object({
  label: core.schemas.string(),
  source: core.schemas.string().optional(),
  region: core.schemas.string().optional(),
  regionFallback: core.schemas.property("region_fallback", core.schemas.boolean().optional()),
  year: core.schemas.string().optional(),
  lcaActivity: core.schemas.property("lca_activity", core.schemas.string().optional()),
  calculationMethod: core.schemas.property(
    "calculation_method",
    core.schemas.lazy(() => serializers.estimation.CalculationMethod).optional()
  ),
});

export declare namespace customActivitySelector {
  interface Raw {
    label: string;
    source?: string | null;
    region?: string | null;
    region_fallback?: boolean | null;
    year?: string | null;
    lca_activity?: string | null;
    calculation_method?: serializers.estimation.CalculationMethod.Raw | null;
  }
}
