/**
 * This file auto-generated by Fern from our API Definition.
 */

export interface BaseRequest {
  /** The region that is relevant for the calculation, as specified by the cloud provider. */
  region: string;
  /** The unit the duration value is in. The values accepted here are the same as in the Time unit. */
  durationUnit?: string;
}
