/**
 * This file auto-generated by Fern from our API Definition.
 */

export interface MemoryRequest {
  /** How much memory you have allocated. As memory requires power to be available even if unused, you should put in the amount of memory that you have available - not only the amount you're using. */
  data: number;
  /** The unit the data value is in. The values accepted here are the same as in the Data unit. */
  dataUnit?: string;
  /** How long the data is stored for. */
  duration: number;
}
