/**
 * This file auto-generated by Fern from our API Definition.
 */

import { ClimatiqApi } from "../../..";

export interface MetadataResponse {
  /** An object where each key is the id for a cloud provider, and the corresponding value contains additional data about that cloud provider. */
  cloudProviders: Record<
    ClimatiqApi.cloudComputing.CloudProvider.RawValue,
    ClimatiqApi.cloudComputing.CloudProviderMetadata
  >;
}
