/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../environments";
import * as core from "../../../core";
import { ClimatiqApi } from "../../..";
import urlJoin from "url-join";
import * as serializers from "../../../serialization";

export declare namespace Client {
  interface Options {
    environment?: environments.Environment | string;
    auth?: {
      token?: core.Supplier<core.BearerToken>;
    };
  }
}

/**
 * Estimation operations are performed to calculate emissions produced by one or more activities, based on multiplying activity data by the appropriate emission factors.
 */
export class Client {
  constructor(private readonly options: Client.Options) {}

  public async estimate(
    request: ClimatiqApi.estimation.EstimateRequest
  ): Promise<ClimatiqApi.estimation.estimate.Response> {
    const response = await core.fetcher({
      url: urlJoin(this.options.environment ?? environments.Environment.Production, "/estimate"),
      method: "POST",
      headers: {
        Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.auth?.token)),
      },
      body: serializers.estimation.EstimateRequest.json(request),
    });
    if (response.ok) {
      return {
        ok: true,
        body: serializers.estimation.EstimateResponse.parse(
          response.body as serializers.estimation.EstimateResponse.Raw
        ),
      };
    }

    return {
      ok: false,
      error: {
        errorName: undefined,
        content: response.error,
        _visit: (visitor) => visitor._other(response.error),
      },
    };
  }

  public async batchEstimate(
    request: ClimatiqApi.estimation.EstimateRequest[]
  ): Promise<ClimatiqApi.estimation.batchEstimate.Response> {
    const response = await core.fetcher({
      url: urlJoin(this.options.environment ?? environments.Environment.Production, "/batch"),
      method: "POST",
      headers: {
        Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.auth?.token)),
      },
      body: serializers.estimation.batchEstimate.Request.json(request),
    });
    if (response.ok) {
      return {
        ok: true,
        body: serializers.estimation.BatchEstimateResponse.parse(
          response.body as serializers.estimation.BatchEstimateResponse.Raw
        ),
      };
    }

    return {
      ok: false,
      error: {
        errorName: undefined,
        content: response.error,
        _visit: (visitor) => visitor._other(response.error),
      },
    };
  }
}
