/**
 * This file auto-generated by Fern from our API Definition.
 */

export const Environment = {
  /**
   * Base URL
   */
  Production: "https://beta3.api.climatiq.io",
} as const;

export type Environment = typeof Environment.Production;
